/* eslint-disable class-methods-use-this */
import { Contract } from '../../src/lib';

export class IntcblockTest extends Contract {
  intValue = GlobalStateKey<uint64>();

  largeIntcblock(): uint64 {
    const a = 1;
    assert(2);
    assert(3);
    assert(4);
    assert(5);
    assert(6);
    assert(7);
    assert(8);
    assert(9);
    assert(10);
    assert(11);
    assert(12);
    assert(13);
    assert(14);
    assert(15);
    assert(16);
    assert(17);
    assert(18);
    assert(19);
    assert(20);
    assert(21);
    assert(22);
    assert(23);
    assert(24);
    assert(25);
    assert(26);
    assert(27);
    assert(28);
    assert(29);
    assert(30);
    assert(31);
    assert(32);
    assert(33);
    assert(34);
    assert(35);
    assert(36);
    assert(37);
    assert(38);
    assert(39);
    assert(40);
    assert(41);
    assert(42);
    assert(43);
    assert(44);
    assert(45);
    assert(46);
    assert(47);
    assert(48);
    assert(49);
    assert(50);
    assert(51);
    assert(52);
    assert(53);
    assert(54);
    assert(55);
    assert(56);
    assert(57);
    assert(58);
    assert(59);
    assert(60);
    assert(61);
    assert(62);
    assert(63);
    assert(64);
    assert(65);
    assert(66);
    assert(67);
    assert(68);
    assert(69);
    assert(70);
    assert(71);
    assert(72);
    assert(73);
    assert(74);
    assert(75);
    assert(76);
    assert(77);
    assert(78);
    assert(79);
    assert(80);
    assert(81);
    assert(82);
    assert(83);
    assert(84);
    assert(85);
    assert(86);
    assert(87);
    assert(88);
    assert(89);
    assert(90);
    assert(91);
    assert(92);
    assert(93);
    assert(94);
    assert(95);
    assert(96);
    assert(97);
    assert(98);
    assert(99);
    assert(100);
    assert(101);
    assert(102);
    assert(103);
    assert(104);
    assert(105);
    assert(106);
    assert(107);
    assert(108);
    assert(109);
    assert(110);
    assert(111);
    assert(112);
    assert(113);
    assert(114);
    assert(115);
    assert(116);
    assert(117);
    assert(118);
    assert(119);
    assert(120);
    assert(121);
    assert(122);
    assert(123);
    assert(124);
    assert(125);
    assert(126);
    assert(127);
    assert(128);
    assert(129);
    assert(130);
    assert(131);
    assert(132);
    assert(133);
    assert(134);
    assert(135);
    assert(136);
    assert(137);
    assert(138);
    assert(139);
    assert(140);
    assert(141);
    assert(142);
    assert(143);
    assert(144);
    assert(145);
    assert(146);
    assert(147);
    assert(148);
    assert(149);
    assert(150);
    assert(151);
    assert(152);
    assert(153);
    assert(154);
    assert(155);
    assert(156);
    assert(157);
    assert(158);
    assert(159);
    assert(160);
    assert(161);
    assert(162);
    assert(163);
    assert(164);
    assert(165);
    assert(166);
    assert(167);
    assert(168);
    assert(169);
    assert(170);
    assert(171);
    assert(172);
    assert(173);
    assert(174);
    assert(175);
    assert(176);
    assert(177);
    assert(178);
    assert(179);
    assert(180);
    assert(181);
    assert(182);
    assert(183);
    assert(184);
    assert(185);
    assert(186);
    assert(187);
    assert(188);
    assert(189);
    assert(190);
    assert(191);
    assert(192);
    assert(193);
    assert(194);
    assert(195);
    assert(196);
    assert(197);
    assert(198);
    assert(199);
    assert(200);
    assert(201);
    assert(202);
    assert(203);
    assert(204);
    assert(205);
    assert(206);
    assert(207);
    assert(208);
    assert(209);
    assert(210);
    assert(211);
    assert(212);
    assert(213);
    assert(214);
    assert(215);
    assert(216);
    assert(217);
    assert(218);
    assert(219);
    assert(220);
    assert(221);
    assert(222);
    assert(223);
    assert(224);
    assert(225);
    assert(226);
    assert(227);
    assert(228);
    assert(229);
    assert(230);
    assert(231);
    assert(232);
    assert(233);
    assert(234);
    assert(235);
    assert(236);
    assert(237);
    assert(238);
    assert(239);
    assert(240);
    assert(241);
    assert(242);
    assert(243);
    assert(244);
    assert(245);
    assert(246);
    assert(247);
    assert(248);
    assert(249);
    assert(250);
    assert(251);
    assert(252);
    assert(253);
    assert(254);
    assert(255);
    assert(256);
    const b = 257;

    return a + b;
  }
}

export class BytecblockTest extends Contract {
  byteValue = GlobalStateKey<bytes>();

  largeBytecblock(): string {
    increaseOpcodeBudget();
    const a = '1';
    this.byteValue.value = '2';
    this.byteValue.value = '3';
    this.byteValue.value = '4';
    this.byteValue.value = '5';
    this.byteValue.value = '6';
    this.byteValue.value = '7';
    this.byteValue.value = '8';
    this.byteValue.value = '9';
    this.byteValue.value = '10';
    this.byteValue.value = '11';
    this.byteValue.value = '12';
    this.byteValue.value = '13';
    this.byteValue.value = '14';
    this.byteValue.value = '15';
    this.byteValue.value = '16';
    this.byteValue.value = '17';
    this.byteValue.value = '18';
    this.byteValue.value = '19';
    this.byteValue.value = '20';
    this.byteValue.value = '21';
    this.byteValue.value = '22';
    this.byteValue.value = '23';
    this.byteValue.value = '24';
    this.byteValue.value = '25';
    this.byteValue.value = '26';
    this.byteValue.value = '27';
    this.byteValue.value = '28';
    this.byteValue.value = '29';
    this.byteValue.value = '30';
    this.byteValue.value = '31';
    this.byteValue.value = '32';
    this.byteValue.value = '33';
    this.byteValue.value = '34';
    this.byteValue.value = '35';
    this.byteValue.value = '36';
    this.byteValue.value = '37';
    this.byteValue.value = '38';
    this.byteValue.value = '39';
    this.byteValue.value = '40';
    this.byteValue.value = '41';
    this.byteValue.value = '42';
    this.byteValue.value = '43';
    this.byteValue.value = '44';
    this.byteValue.value = '45';
    this.byteValue.value = '46';
    this.byteValue.value = '47';
    this.byteValue.value = '48';
    this.byteValue.value = '49';
    this.byteValue.value = '50';
    this.byteValue.value = '51';
    this.byteValue.value = '52';
    this.byteValue.value = '53';
    this.byteValue.value = '54';
    this.byteValue.value = '55';
    this.byteValue.value = '56';
    this.byteValue.value = '57';
    this.byteValue.value = '58';
    this.byteValue.value = '59';
    this.byteValue.value = '60';
    this.byteValue.value = '61';
    this.byteValue.value = '62';
    this.byteValue.value = '63';
    this.byteValue.value = '64';
    this.byteValue.value = '65';
    this.byteValue.value = '66';
    this.byteValue.value = '67';
    this.byteValue.value = '68';
    this.byteValue.value = '69';
    this.byteValue.value = '70';
    this.byteValue.value = '71';
    this.byteValue.value = '72';
    this.byteValue.value = '73';
    this.byteValue.value = '74';
    this.byteValue.value = '75';
    this.byteValue.value = '76';
    this.byteValue.value = '77';
    this.byteValue.value = '78';
    this.byteValue.value = '79';
    this.byteValue.value = '80';
    this.byteValue.value = '81';
    this.byteValue.value = '82';
    this.byteValue.value = '83';
    this.byteValue.value = '84';
    this.byteValue.value = '85';
    this.byteValue.value = '86';
    this.byteValue.value = '87';
    this.byteValue.value = '88';
    this.byteValue.value = '89';
    this.byteValue.value = '90';
    this.byteValue.value = '91';
    this.byteValue.value = '92';
    this.byteValue.value = '93';
    this.byteValue.value = '94';
    this.byteValue.value = '95';
    this.byteValue.value = '96';
    this.byteValue.value = '97';
    this.byteValue.value = '98';
    this.byteValue.value = '99';
    this.byteValue.value = '100';
    this.byteValue.value = '101';
    this.byteValue.value = '102';
    this.byteValue.value = '103';
    this.byteValue.value = '104';
    this.byteValue.value = '105';
    this.byteValue.value = '106';
    this.byteValue.value = '107';
    this.byteValue.value = '108';
    this.byteValue.value = '109';
    this.byteValue.value = '110';
    this.byteValue.value = '111';
    this.byteValue.value = '112';
    this.byteValue.value = '113';
    this.byteValue.value = '114';
    this.byteValue.value = '115';
    this.byteValue.value = '116';
    this.byteValue.value = '117';
    this.byteValue.value = '118';
    this.byteValue.value = '119';
    this.byteValue.value = '120';
    this.byteValue.value = '121';
    this.byteValue.value = '122';
    this.byteValue.value = '123';
    this.byteValue.value = '124';
    this.byteValue.value = '125';
    this.byteValue.value = '126';
    this.byteValue.value = '127';
    this.byteValue.value = '128';
    this.byteValue.value = '129';
    this.byteValue.value = '130';
    this.byteValue.value = '131';
    this.byteValue.value = '132';
    this.byteValue.value = '133';
    this.byteValue.value = '134';
    this.byteValue.value = '135';
    this.byteValue.value = '136';
    this.byteValue.value = '137';
    this.byteValue.value = '138';
    this.byteValue.value = '139';
    this.byteValue.value = '140';
    this.byteValue.value = '141';
    this.byteValue.value = '142';
    this.byteValue.value = '143';
    this.byteValue.value = '144';
    this.byteValue.value = '145';
    this.byteValue.value = '146';
    this.byteValue.value = '147';
    this.byteValue.value = '148';
    this.byteValue.value = '149';
    this.byteValue.value = '150';
    this.byteValue.value = '151';
    this.byteValue.value = '152';
    this.byteValue.value = '153';
    this.byteValue.value = '154';
    this.byteValue.value = '155';
    this.byteValue.value = '156';
    this.byteValue.value = '157';
    this.byteValue.value = '158';
    this.byteValue.value = '159';
    this.byteValue.value = '160';
    this.byteValue.value = '161';
    this.byteValue.value = '162';
    this.byteValue.value = '163';
    this.byteValue.value = '164';
    this.byteValue.value = '165';
    this.byteValue.value = '166';
    this.byteValue.value = '167';
    this.byteValue.value = '168';
    this.byteValue.value = '169';
    this.byteValue.value = '170';
    this.byteValue.value = '171';
    this.byteValue.value = '172';
    this.byteValue.value = '173';
    this.byteValue.value = '174';
    this.byteValue.value = '175';
    this.byteValue.value = '176';
    this.byteValue.value = '177';
    this.byteValue.value = '178';
    this.byteValue.value = '179';
    this.byteValue.value = '180';
    this.byteValue.value = '181';
    this.byteValue.value = '182';
    this.byteValue.value = '183';
    this.byteValue.value = '184';
    this.byteValue.value = '185';
    this.byteValue.value = '186';
    this.byteValue.value = '187';
    this.byteValue.value = '188';
    this.byteValue.value = '189';
    this.byteValue.value = '190';
    this.byteValue.value = '191';
    this.byteValue.value = '192';
    this.byteValue.value = '193';
    this.byteValue.value = '194';
    this.byteValue.value = '195';
    this.byteValue.value = '196';
    this.byteValue.value = '197';
    this.byteValue.value = '198';
    this.byteValue.value = '199';
    this.byteValue.value = '200';
    this.byteValue.value = '201';
    this.byteValue.value = '202';
    this.byteValue.value = '203';
    this.byteValue.value = '204';
    this.byteValue.value = '205';
    this.byteValue.value = '206';
    this.byteValue.value = '207';
    this.byteValue.value = '208';
    this.byteValue.value = '209';
    this.byteValue.value = '210';
    this.byteValue.value = '211';
    this.byteValue.value = '212';
    this.byteValue.value = '213';
    this.byteValue.value = '214';
    this.byteValue.value = '215';
    this.byteValue.value = '216';
    this.byteValue.value = '217';
    this.byteValue.value = '218';
    this.byteValue.value = '219';
    this.byteValue.value = '220';
    this.byteValue.value = '221';
    this.byteValue.value = '222';
    this.byteValue.value = '223';
    this.byteValue.value = '224';
    this.byteValue.value = '225';
    this.byteValue.value = '226';
    this.byteValue.value = '227';
    this.byteValue.value = '228';
    this.byteValue.value = '229';
    this.byteValue.value = '230';
    this.byteValue.value = '231';
    this.byteValue.value = '232';
    this.byteValue.value = '233';
    this.byteValue.value = '234';
    this.byteValue.value = '235';
    this.byteValue.value = '236';
    this.byteValue.value = '237';
    this.byteValue.value = '238';
    this.byteValue.value = '239';
    this.byteValue.value = '240';
    this.byteValue.value = '241';
    this.byteValue.value = '242';
    this.byteValue.value = '243';
    this.byteValue.value = '244';
    this.byteValue.value = '245';
    this.byteValue.value = '246';
    this.byteValue.value = '247';
    this.byteValue.value = '248';
    this.byteValue.value = '249';
    this.byteValue.value = '250';
    this.byteValue.value = '251';
    this.byteValue.value = '252';
    this.byteValue.value = '253';
    this.byteValue.value = '254';
    this.byteValue.value = '255';
    this.byteValue.value = '256';
    const b = '257';
    this.byteValue.value =
      'This is a fairly long byteslice that should be put in the consant block because it is so long';

    return a + b;
  }
}
